### ISSUE TITLE
Add ability of manage capabilities to SSO specific WP roles on admin page

### ISSUE THREAD

**Issue by Claymanus** [edemo/wp_oauth_plugin#5] opened 2015-05-31 16:35 UTC
maybe, if sombody wants it

**Comment by magwas** [comment] 2015-12-30 19:08
which assurance will represent which role

**Comment by magwas** [comment] 2015-12-30 19:10
capability management -> wontfix, use capa manager
role- assurance binding ->duplicate of #3

**Closed as completed by magwas** 2015-12-30 19:10 UTC
Labels: duplicate, wontfix
